spring:
  application:
    name: ws-configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rathodsantosh/cloud-config-server.git
          skip-ssl-validation: true
server:
  port: 8888
